FORMAT: 1A
HOST: http://localhost:8000/

# Messages

Messages is a simple API allowing users to send and receive messages.

# Group Authentication

## Signup [/accounts/signup/]

### Create an Account [POST]

+ Request (application/json)
    
        {
            "username": <username>,
            "password1": <password>,
            "password2": <password>
        }

+ Response 201 (application/json)

    + Body
    
            {
                "id": <user_id>,
                "username": <username>,
                "first_name": <first name>,
                "last_name": <last name>
            }

+ Response 400 (application/json)

        Returned if the specified username is already taken, the passwords 
        do not match, or fields are blank or missing.


## Login [/accounts/login/]

### Login to account [POST]

You must provide your username and pasword. In exchange you will receive
access token, which expires every 5 minutes, and a refresh token, which
expires every 24 hours.

+ Request (application/json)

        {
            "username": <username>,
            "password": <password>
        }

+ Response 200 (application/json)

    + Body

            {
                "refresh": <refresh token>,
                "access": <access token>
            }
            
+ Response 401 (application/json)

    Returned if the username or password is incorrect.

    + Body

            {
                "detail": "No active account found with the given credentials"
            }
            
+ Response 400 (application/json)

        Returned if fields are blank or missing.

            
# Group Profiles

## User profile [/{username}/]

### Get a user's profile [GET]

+ Request (application/json)

    + Headers
        
            Authorization: <access token>

+ Response 200 (application/json)

    + Body
        
            {
                "username": <username>,
                "first_name": <first name>,
                "last_name": <last name>
            }