# Generated by Django 3.0.8 on 2020-08-02 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Friends'), (2, 'Blocked')])),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_profiles', to='profiles.Profile')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_profiles', to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Accepted'), (2, 'Denied'), (3, 'Pending'), (4, 'Canceled')])),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='profiles.Profile')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to='profiles.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='friend_requests',
            field=models.ManyToManyField(related_name='incoming_requests', through='profiles.FriendRequest', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='relationships',
            field=models.ManyToManyField(related_name='_profile_relationships_+', through='profiles.Relationship', to='profiles.Profile'),
        ),
    ]
